INSERT INTO tb_category(name, created_at) VALUES ('Books', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Computers', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Clothing', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Home & Kitchen', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Toys & Games', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Health & Personal Care', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Sports & Outdoors', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Beauty', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Automotive', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Garden', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Office Supplies', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Music', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Movies & TV', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Video Games', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Jewelry', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Shoes', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Grocery', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Baby Products', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Industrial & Scientific', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Tools & Home Improvement', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Arts & Crafts', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Cell Phones & Accessories', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Camera & Photo', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Watches', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Musical Instruments', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Software', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Luggage & Travel Gear', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Handmade', NOW());
